CREATE DATABASE IF NOT EXISTS deli_shey;

USE deli_shey;

CREATE TABLE IF NOT EXISTS roles (

    id INT AUTO_INCREMENT PRIMARY KEY,

    name VARCHAR(50) UNIQUE NOT NULL

);

CREATE TABLE IF NOT EXISTS users (

    id INT AUTO_INCREMENT PRIMARY KEY,

    name VARCHAR(100) NOT NULL,

    email VARCHAR(100) UNIQUE NOT NULL,

    password VARCHAR(255) NOT NULL,

    role_id INT NOT NULL DEFAULT 2,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (role_id)
    REFERENCES roles(id)

);

CREATE TABLE IF NOT EXISTS products (

    id INT AUTO_INCREMENT PRIMARY KEY,

    name VARCHAR(100),

    price DECIMAL(10,2),

    category VARCHAR(100),

    description TEXT,

    image TEXT,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);